// Generated by REDLINE Core
#include "stdlib/rl_io.hpp"
#include <string>


int main() {
    const int speed = 50;
    if (speed > 100) {
    rl::print("Warning: Too Fast!");
    } else {
    rl::print("Speed is safe.");
    const std::string weather = "Rainy";
    rl::print("Status check complete.");
    }
    return 0;
}