// Generated by REDLINE Core
#include "stdlib/rl_io.hpp"
#include <string>

int get_boost(int base) {
    return base*2;
}


int main() {
    const std::string ship_name = "Redline-One";
    int velocity = 100;
    const int boost = get_boost(velocity);
    rl::print(ship_name);
    rl::print("Velocity with boost:");
    rl::print(boost);
    return 0;
}