// examples/v0.7_cpp_interop/main.cpp
#include <iostream>
#include "redline_lib.hpp" // This header will be generated by the REDLINE compiler

int main() {
    std::cout << "--- C++ Interop Demo ---" << std::endl;

    // 1. Call a REDLINE function
    int sum = rl::add_numbers(10, 20);
    std::cout << "Sum from REDLINE: " << sum << std::endl;

    // 2. Use a REDLINE class
    rl::Greeter g("Greetings");
    g.greet("C++ User");

    return 0;
}
